name: Moodle Scheduler

on:
  schedule:
    - cron: '55 6 * * 1-5'       # Checkin at 06:55 UTC (08:55 Brussels)  Monday to Friday
    - cron: '30 10 * * 1-5'      # Checkout at 10:30 UTC (12:30 Brussels) Monday to Friday
    - cron: '25 11 * * 1-5'      # Checkin at 11:25 UTC (13:25 Brussels)  Monday to Friday
    - cron: '0 15 * * 1-5'       # Checkout at 15:00 UTC (17:00 Brussels) Monday to Friday

  workflow_dispatch:

jobs:
  run-scheduler:
    runs-on: ubuntu-latest

    env:
      MOODLE_USERNAME: ${{ secrets.MOODLE_USERNAME }}
      MOODLE_PASSWORD: ${{ secrets.MOODLE_PASSWORD }}
      ICAL_URL: ${{ secrets.ICAL_URL }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install

      - name: Run main scheduler
        run: python main_scheduler.py
